plugins {
    id 'com.android.application'
    id 'kotlin-android'
    id 'kotlin-kapt'
}

android {
    compileSdkVersion rootProject.android.compileSdk
    buildToolsVersion "30.0.3"

    defaultConfig {
        applicationId rootProject.android.applicationId
        minSdkVersion rootProject.android.minSdk
        targetSdkVersion rootProject.android.targetSdk
        versionCode rootProject.android.versionCode
        versionName rootProject.android.versionName

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        dataBinding = true
        viewBinding true
    }
}

dependencies {

    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation rootProject.depsLibs.coreKtx
    implementation rootProject.depsLibs.appcompat
    implementation rootProject.depsLibs.material
    implementation rootProject.depsLibs.constraintlayout
    testImplementation rootProject.depsLibs.junit
    androidTestImplementation rootProject.depsLibs.extJunit
    androidTestImplementation rootProject.depsLibs.espressoCore
    implementation rootProject.depsLibs.navigationFragment
    implementation rootProject.depsLibs.navigationUI

    compileOnly rootProject.depsLibs.glide
    kapt rootProject.depsLibs.glideCompiler


    implementation project(path: ':framework_mvvm')
}